version: 2.1
jobs:
  compile:
    docker:
      - image: ubuntu:latest
    steps:
      - run: apt update && apt dist-upgrade -y && apt upgrade -y
      - run: apt autoremove -y && apt install git -y && apt install wget -y
      - run: git clone --depth=1 -j$(nproc --all) -b riva11-4 https://github.com/RandomiDn/android-kernel-xiaomi-riva --single-branch
      - run: export token=$token
      - run: su -c ./build-kernel.sh

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile