version: 2.1

jobs:
  build:
    docker:
      - image: smaant/lein-flyway:2.7.1-4.0.3
        auth:
          username: arrayfs
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Update TOKEN and Define Environment Variable at Runtime
          command: |
            echo 'export TOKEN=$token' >> $BASH_ENV
            echo 'CHAT_ID=$chat_id' >> $BASH_ENV
            echo 'export Environment="FOO"' >>
            bash $BASH_ENV