version: 2.1
jobs:
  compile:
    docker:
      - image: ubuntu:latest
    steps:
      - run: export token=$token
      - run: apt update && apt dist-upgrade -y && apt upgrade -y
      - run: apt autoremove && apt install wget -y
      - run: wget https://raw.githubusercontent.com/RandomiDn/android-kernel-xiaomi-riva/riva11-4/build-kernel.sh
      - run: chmod 755 build-kernel.sh && sh build-kernel.sh

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile