version: 2.1
jobs:
  compile:
    docker:
      - image: ubuntu:latest
    steps:
      - run: export token=$token
      - run: apt update && apt dist-upgrade -y && apt upgrade -y
      - run: apt autoremove -y
      - run: bash /android-kernel-xiaomi-riva/build-kernel.sh

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile