version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: arrayfs
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
  - run:
      name: Setup Environment Variables
      command: |
        echo 'export token=$token' >> $BASH_ENV