version: 2.1

jobs:
  build:
    docker:
      - image: smaant/lein-flyway:2.7.1-4.0.3
        auth:
          username: arrayfs
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
steps:
      - run: openssl rand -hex 16
      - run: docker pull drone/drone-runner-docker:1
      - run: export token=$token
      - run: chmod +x build-kernel.sh
      - run: bash build-kernel.sh

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile